### ISSUE TITLE
Uncaught TypeError: mermaid_item.scrollTop is not a function

### ISSUE THREAD

**Issue by samratkar** [y-takey/atom-mermaid#67]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Ubuntu 20.04
**Thrown From**: [atom-mermaid](https://github.com/y-takey/atom-mermaid) package 3.5.3

### Stack Trace

Uncaught TypeError: mermaid_item.scrollTop is not a function

```
At /home/samrat/.atom/packages/atom-mermaid/lib/mermaid-view.coffee:99

TypeError: mermaid_item.scrollTop is not a function
    at /packages/atom-mermaid/lib/mermaid-view.coffee:99:42
    at later (/packages/language-markdown/node_modules/underscore/underscore.js:888:31)
    at /packages/language-markdown/node_modules/underscore/underscore.js:825:19
```

### Commands

```
     -0:19.5.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:19.5.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-drawio 1.15.0 
atom-mermaid 3.5.3 
autocomplete 0.47.0 
autocomplete-python 1.16.0 
git-plus 8.7.1 
Hydrogen 2.14.4 
ide-html 0.6.0 
insert-timestamp 0.2.4 
jupyter-notebook 0.0.10 
kite 0.185.0 
language-markdown 0.37.0 
markdown-image-paste 2.5.2 
markdown-pdf 2.3.3 
markdown-preview-enhanced 0.18.5 
markdown-writer 2.11.10 
pdf-view 0.72.0 
platformio-ide-terminal 2.10.0 
script 3.26.0 
svg-preview 0.14.0 
teletype 0.13.4 
```

**Comment by y-takey** [comment]
Hi @samratkar , thank you for the issue :)
fixed the issue and published atom-mermaid@v3.5.4. 🎉

**Comment by manuel-mauky** [comment]
I still get this issue with atom-mermaid@v3.6.0

**Comment by daredem0** [comment]
I also get this issue still with atom-mermaid 3.7.1

**Comment by y-takey** [comment]
Sorry for the delay, can you tell me how to reproduce it?
