### ISSUE TITLE
Uncaught Error: Package subpath './dist/mermaid.js' is not defined by "exports" in $ATOM_HOME/pac...

### ISSUE THREAD

**Issue by tbolsh** [y-takey/atom-mermaid#79]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.63.1 x64
**Electron**: 11.5.0
**OS**: Microsoft Windows 11 Home
**Thrown From**: [atom-mermaid](https://github.com/y-takey/atom-mermaid) package 3.7.1

### Stack Trace

Uncaught Error: Package subpath './dist/mermaid.js' is not defined by "exports" in C:\Users\tbols\.atom\packages\atom-mermaid\node_modules\mermaid\package.json

```
At internal/modules/cjs/loader.js:497

Error [ERR_PACKAGE_PATH_NOT_EXPORTED] [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/mermaid.js' is not defined by "exports" in C:\Users\tbols\.atom\packages\atom-mermaid\node_modules\mermaid\package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Module._resolveFilename (internal/modules/cjs/loader.js:959:27)
    at o._resolveFilename (electron/js2c/renderer_init.js:35:917)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.63.1/resources/app/static/<embedded>:11:157942)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.63.1/resources/app/static/<embedded>:11:149229)
    at /packages/atom-mermaid/lib/mermaid-view.coffee:6:11)
    at /packages/atom-mermaid/lib/mermaid-view.coffee:1:1)
    at /packages/atom-mermaid/lib/mermaid-view.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.63.1/resources/app/static/<embedded>:11:149913)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.63.1/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.63.1/resources/app/static/<embedded>:11:149229)
    at /packages/atom-mermaid/lib/atom-mermaid.coffee:2:35)
    at /packages/atom-mermaid/lib/atom-mermaid.coffee:1:1)
    at /packages/atom-mermaid/lib/atom-mermaid.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.63.1/resources/app/static/<embedded>:11:149913)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.63.1/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:72:18)
    at customRequire (~/AppData/Local/atom/app-1.63.1/resources/app/static/<embedded>:1:821096)
    at requireModule (~/AppData/Local/atom/app-1.63.1/resources/app/static/<embedded>:14:1223077)
```

### Commands

```
```

### Non-Core Packages

```
atom-mermaid 3.7.1 
language-mermaid 0.6.0 
```

**Comment by y-takey** [comment]
Hi @tbolsh , Thanks for the report :)
But the atom editor be archived, there are no maintenance plans for this package as well.

FYI: https://github.blog/2022-06-08-sunsetting-atom/
